ALTER TABLE project_platforms
ADD COLUMN is_default TINYINT(1) DEFAULT 0;

ALTER TABLE project_platforms
ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE projects
ADD COLUMN is_active TINYINT(1) DEFAULT 1;

ALTER TABLE platforms
ADD COLUMN is_active TINYINT(1) DEFAULT 1;

ALTER TABLE task_statuses
ADD COLUMN is_active TINYINT(1) DEFAULT 1;

ALTER TABLE task_sources
ADD COLUMN is_active TINYINT(1) DEFAULT 1;

ALTER TABLE task_types
ADD COLUMN is_active TINYINT(1) DEFAULT 1;